#
# Creates some C++ code to populate our test structure with tests
# which are automatically extracted from Markus Kuhn's UTF-8-test.txt
#
# Some tests aren't extracted (the first, and those split over multiple
# lines). Going for the low-hanging fruit here.
# 
# Filters stdin to stdout
#

use bytes;

$lastReference = 0;

print "//This file is autogenerated by convert-kuhn-tests.pl and the Makefile\n";
print "//will overwrite and delete it!\n\n";

while(<>) {
	if(/^(\d\.\d\.\d+)\s+/) { $lastReference = "Kuhn " . $1; }
	if($lastReference and /"(\S+)"/) {
	   	print "v.clear();\n";
		for($i = 0; $i < length($1); $i++) {
			print "v.push_back(0x" . sprintf("%02X", ord(substr($1,$i))) . "); ";
		}

		print "\n";
		print "tests.push_back(OneTest(\"$lastReference\", v));\n";
		print "\n";
	}
}

